"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-01 12:18:50.389377
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
import app.db


revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_settings'))
    )
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('source', sa.Enum('user', 'ai', 'scheduler', 'import', 'calendar', 'system', name='audit_source', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.CheckConstraint("source IN ('user', 'ai', 'scheduler', 'import', 'calendar', 'system')", name='audit_source'),
    sa.CheckConstraint("source IN ('user', 'ai', 'scheduler', 'import', 'calendar', 'system')", name=op.f('ck_audit_log_audit_source')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_at'), ['at'], unique=False)
        batch_op.create_index('ix_audit_log_entity', ['entity_type', 'entity_id'], unique=False)

    op.create_table('import_batches',
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('file_sha256', sa.String(length=64), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('rolled_back_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_batches'))
    )
    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_batches_file_sha256'), ['file_sha256'], unique=False)

    op.create_table('projects',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('status', sa.Enum('active', 'archived', name='project_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('active', 'archived')", name='project_status'),
    sa.CheckConstraint("status IN ('active', 'archived')", name=op.f('ck_projects_project_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects')),
    sa.UniqueConstraint('name', name=op.f('uq_projects_name'))
    )
    op.create_table('tasks',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'critical', name='task_priority', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('status', sa.Enum('inbox', 'planned', 'in_progress', 'blocked', 'completed', 'cancelled', name='task_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('deadline', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('earliest_start', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('planned_date', sa.Date(), nullable=True),
    sa.Column('preferred_time', sa.Enum('morning', 'afternoon', 'evening', name='task_preferred_time', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('energy_requirement', sa.Enum('low', 'medium', 'high', name='task_energy', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('importance', sa.SmallInteger(), nullable=True),
    sa.Column('urgency', sa.SmallInteger(), nullable=True),
    sa.Column('recurrence_rule', sa.String(length=500), nullable=True),
    sa.Column('recurrence_parent_id', sa.Uuid(), nullable=True),
    sa.Column('occurrence_date', sa.Date(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('source', sa.Enum('user', 'ai', 'import', 'recurrence', name='task_source', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('pending_approval', sa.Boolean(), nullable=False),
    sa.Column('completed_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.CheckConstraint("energy_requirement IN ('low', 'medium', 'high')", name='task_energy'),
    sa.CheckConstraint("energy_requirement IN ('low', 'medium', 'high')", name=op.f('ck_tasks_task_energy')),
    sa.CheckConstraint("preferred_time IN ('morning', 'afternoon', 'evening')", name='task_preferred_time'),
    sa.CheckConstraint("preferred_time IN ('morning', 'afternoon', 'evening')", name=op.f('ck_tasks_task_preferred_time')),
    sa.CheckConstraint("priority IN ('low', 'medium', 'high', 'critical')", name='task_priority'),
    sa.CheckConstraint("priority IN ('low', 'medium', 'high', 'critical')", name=op.f('ck_tasks_task_priority')),
    sa.CheckConstraint("source IN ('user', 'ai', 'import', 'recurrence')", name='task_source'),
    sa.CheckConstraint("source IN ('user', 'ai', 'import', 'recurrence')", name=op.f('ck_tasks_task_source')),
    sa.CheckConstraint("status IN ('inbox', 'planned', 'in_progress', 'blocked', 'completed', 'cancelled')", name='task_status'),
    sa.CheckConstraint("status IN ('inbox', 'planned', 'in_progress', 'blocked', 'completed', 'cancelled')", name=op.f('ck_tasks_task_status')),
    sa.CheckConstraint('estimated_minutes IS NULL OR estimated_minutes > 0', name=op.f('ck_tasks_estimate_positive')),
    sa.CheckConstraint('importance IS NULL OR importance BETWEEN 1 AND 5', name=op.f('ck_tasks_importance_range')),
    sa.CheckConstraint('urgency IS NULL OR urgency BETWEEN 1 AND 5', name=op.f('ck_tasks_urgency_range')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_tasks_project_id_projects'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recurrence_parent_id'], ['tasks.id'], name=op.f('fk_tasks_recurrence_parent_id_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks')),
    sa.UniqueConstraint('recurrence_parent_id', 'occurrence_date', name='uq_tasks_occurrence')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_deadline'), ['deadline'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_planned_date'), ['planned_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_recurrence_parent_id'), ['recurrence_parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_status'), ['status'], unique=False)

    op.create_table('focus_sessions',
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.Enum('work', 'rest', name='session_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('state', sa.Enum('running', 'paused', 'finished', name='session_state', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('source', sa.Enum('timer', 'manual', 'import', name='session_source', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('start_time', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('end_time', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('tz_offset_minutes', sa.Integer(), nullable=False),
    sa.Column('planned_duration_s', sa.Integer(), nullable=True),
    sa.Column('active_duration_s', sa.Integer(), nullable=True),
    sa.Column('paused_duration_s', sa.Integer(), nullable=False),
    sa.Column('paused_since', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('pause_count', sa.Integer(), nullable=True),
    sa.Column('end_reason', sa.Enum('completed', 'stopped', 'skipped', 'switched', 'unknown', name='session_end_reason', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('outcome', sa.Enum('completed', 'partial', 'blocked', 'abandoned', name='session_outcome', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('task_title_snapshot', sa.String(length=500), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('category_snapshot', sa.String(length=100), nullable=True),
    sa.Column('external_id', sa.String(length=200), nullable=True),
    sa.Column('import_batch_id', sa.Uuid(), nullable=True),
    sa.Column('quality_flags', sa.JSON(), nullable=False),
    sa.Column('exclude_from_stats', sa.Boolean(), nullable=False),
    sa.Column('voided_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.CheckConstraint("end_reason IN ('completed', 'stopped', 'skipped', 'switched', 'unknown')", name='session_end_reason'),
    sa.CheckConstraint("end_reason IN ('completed', 'stopped', 'skipped', 'switched', 'unknown')", name=op.f('ck_focus_sessions_session_end_reason')),
    sa.CheckConstraint("outcome IN ('completed', 'partial', 'blocked', 'abandoned')", name='session_outcome'),
    sa.CheckConstraint("outcome IN ('completed', 'partial', 'blocked', 'abandoned')", name=op.f('ck_focus_sessions_session_outcome')),
    sa.CheckConstraint("source IN ('timer', 'manual', 'import')", name='session_source'),
    sa.CheckConstraint("source IN ('timer', 'manual', 'import')", name=op.f('ck_focus_sessions_session_source')),
    sa.CheckConstraint("state IN ('running', 'paused', 'finished')", name='session_state'),
    sa.CheckConstraint("state IN ('running', 'paused', 'finished')", name=op.f('ck_focus_sessions_session_state')),
    sa.CheckConstraint("type IN ('work', 'rest')", name='session_type'),
    sa.CheckConstraint("type IN ('work', 'rest')", name=op.f('ck_focus_sessions_session_type')),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], name=op.f('fk_focus_sessions_import_batch_id_import_batches'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_focus_sessions_project_id_projects'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_focus_sessions_task_id_tasks'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_focus_sessions')),
    sa.UniqueConstraint('source', 'external_id', name='uq_focus_sessions_external')
    )
    with op.batch_alter_table('focus_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_focus_sessions_import_batch_id'), ['import_batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_focus_sessions_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_focus_sessions_start_time'), ['start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_focus_sessions_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_focus_sessions_task_id'), ['task_id'], unique=False)

    op.create_table('task_dependencies',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('depends_on_id', sa.Uuid(), nullable=False),
    sa.Column('strict', sa.Boolean(), nullable=False),
    sa.CheckConstraint('task_id <> depends_on_id', name=op.f('ck_task_dependencies_not_self')),
    sa.ForeignKeyConstraint(['depends_on_id'], ['tasks.id'], name=op.f('fk_task_dependencies_depends_on_id_tasks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_task_dependencies_task_id_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'depends_on_id', name=op.f('pk_task_dependencies'))
    )
    with op.batch_alter_table('task_dependencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_dependencies_depends_on_id'), ['depends_on_id'], unique=False)

    op.create_table('import_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('imported', 'duplicate', 'invalid', name='import_record_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.CheckConstraint("status IN ('imported', 'duplicate', 'invalid')", name='import_record_status'),
    sa.CheckConstraint("status IN ('imported', 'duplicate', 'invalid')", name=op.f('ck_import_records_import_record_status')),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], name=op.f('fk_import_records_batch_id_import_batches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['focus_sessions.id'], name=op.f('fk_import_records_session_id_focus_sessions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_records'))
    )
    with op.batch_alter_table('import_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_records_batch_id'), ['batch_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_records_batch_id'))

    op.drop_table('import_records')
    with op.batch_alter_table('task_dependencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_dependencies_depends_on_id'))

    op.drop_table('task_dependencies')
    with op.batch_alter_table('focus_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_focus_sessions_task_id'))
        batch_op.drop_index(batch_op.f('ix_focus_sessions_state'))
        batch_op.drop_index(batch_op.f('ix_focus_sessions_start_time'))
        batch_op.drop_index(batch_op.f('ix_focus_sessions_project_id'))
        batch_op.drop_index(batch_op.f('ix_focus_sessions_import_batch_id'))

    op.drop_table('focus_sessions')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_tasks_recurrence_parent_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_project_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_planned_date'))
        batch_op.drop_index(batch_op.f('ix_tasks_deadline'))
        batch_op.drop_index(batch_op.f('ix_tasks_category'))

    op.drop_table('tasks')
    op.drop_table('projects')
    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_batches_file_sha256'))

    op.drop_table('import_batches')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_log_entity')
        batch_op.drop_index(batch_op.f('ix_audit_log_at'))

    op.drop_table('audit_log')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
