"""calendar cache

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-01 21:43:08
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.db

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "calendar_accounts",
        sa.Column(
            "provider",
            sa.Enum(
                "ical",
                "google",
                name="calendar_provider",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "connected",
                "error",
                name="calendar_account_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("feed_url_encrypted", sa.Text(), nullable=True),
        sa.Column("feed_url_sha256", sa.String(length=64), nullable=True),
        sa.Column("feed_host", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", app.db.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", app.db.UTCDateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calendar_accounts")),
    )
    with op.batch_alter_table("calendar_accounts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_calendar_accounts_feed_url_sha256"), ["feed_url_sha256"], unique=False
        )

    op.create_table(
        "calendars",
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("provider_calendar_id", sa.String(length=500), nullable=False),
        sa.Column("summary", sa.String(length=200), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=True),
        sa.Column("color", sa.String(length=20), nullable=True),
        sa.Column("selected", sa.Boolean(), nullable=False),
        sa.Column("all_day_busy", sa.Boolean(), nullable=False),
        sa.Column("sync_token", sa.String(length=500), nullable=True),
        sa.Column("http_last_modified", sa.String(length=100), nullable=True),
        sa.Column("last_synced_at", app.db.UTCDateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(length=1000), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", app.db.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", app.db.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["calendar_accounts.id"],
            name=op.f("fk_calendars_account_id_calendar_accounts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calendars")),
        sa.UniqueConstraint("account_id", "provider_calendar_id", name=op.f("uq_calendars_account_id")),
    )
    with op.batch_alter_table("calendars", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_calendars_account_id"), ["account_id"], unique=False)

    op.create_table(
        "calendar_events",
        sa.Column("calendar_id", sa.Uuid(), nullable=False),
        sa.Column("provider_event_id", sa.String(length=1000), nullable=False),
        sa.Column("recurring_event_id", sa.String(length=1000), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("location", sa.String(length=500), nullable=True),
        sa.Column("start_time", app.db.UTCDateTime(timezone=True), nullable=False),
        sa.Column("end_time", app.db.UTCDateTime(timezone=True), nullable=False),
        sa.Column("all_day", sa.Boolean(), nullable=False),
        sa.Column("busy", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "confirmed",
                "tentative",
                "cancelled",
                name="calendar_event_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "origin",
            sa.Enum(
                "USER_CREATED_EVENT",
                "APP_GENERATED_EVENT",
                name="event_origin",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("etag", sa.String(length=64), nullable=False),
        sa.Column("remote_updated_at", app.db.UTCDateTime(timezone=True), nullable=True),
        sa.Column("synced_at", app.db.UTCDateTime(timezone=True), nullable=False),
        sa.Column("raw", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", app.db.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", app.db.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["calendar_id"],
            ["calendars.id"],
            name=op.f("fk_calendar_events_calendar_id_calendars"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calendar_events")),
        sa.UniqueConstraint("calendar_id", "provider_event_id", name=op.f("uq_calendar_events_calendar_id")),
    )
    with op.batch_alter_table("calendar_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_calendar_events_calendar_id"), ["calendar_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_calendar_events_end_time"), ["end_time"], unique=False)
        batch_op.create_index(batch_op.f("ix_calendar_events_start_time"), ["start_time"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("calendar_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_calendar_events_start_time"))
        batch_op.drop_index(batch_op.f("ix_calendar_events_end_time"))
        batch_op.drop_index(batch_op.f("ix_calendar_events_calendar_id"))

    op.drop_table("calendar_events")
    with op.batch_alter_table("calendars", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_calendars_account_id"))

    op.drop_table("calendars")
    with op.batch_alter_table("calendar_accounts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_calendar_accounts_feed_url_sha256"))

    op.drop_table("calendar_accounts")
    # ### end Alembic commands ###
